listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=192.168.1.207
external-ip=96.228.35.4
realm=form.services
server-name=form.services
lt-cred-mech
use-auth-secret
static-auth-secret=9297f065e7a3a604fb0936aecdbd9758455e39f8ddd1667d684d7cba7286ff66
cert=/Users/fischergrant/formservices/config/tls/cert.pem
pkey=/Users/fischergrant/formservices/config/tls/key.pem
log-file=/Users/fischergrant/formservices/logs/coturn.log
no-stdout-log
fingerprint
